---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: 'present'
    name:
      - zsh
      - libcap-ng-dev

- name: Remove the old installer
  file:
    path: "{{ omz_installer }}"
    state: absent

- name: Remove the old repo
  file:
    path: "{{ omz_installer }}"
    state: absent

- name: Ensure the antigen installer folder NOT exist
  file:
    path: "{{ antigen_installer | dirname }}"
    state: absent

- name: Change the default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
    state: present
    append: yes
    groups: 'dialout'

- name: Remove old custom plugins
  file:
    path: "{{ item.dst }}"
    state: absent
  with_items: "{{ zsh_custom_plugs }}"

- name: Remove old custom plugin folder
  file:
    path: "{{ omz_custom_dir }}"
    state: absent

- name: Comment out the conda init block from [bash/zsh]rc files to speed up terminal startup time, block before
  ansible.builtin.lineinfile:
    path: "{{ zshrc_path }}"
    insertbefore: '>>> conda initialize >>>'
    line: ": <<'EOF'"

- name: Comment out the conda init block from [bash/zsh]rc files to speed up terminal startup time, block after
  ansible.builtin.lineinfile:
    path: "{{ zshrc_path }}"
    insertafter: '<<< conda initialize <<<'
    line: "EOF"
