---
- name: Download and Add Powershell Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add Powershell Repository into /etc/apt/sources.list - Bionic
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
    state: present

- name: Install Powershell
  become: true
  apt:
    pkg: powershell
    state: present

- name: Make sure we can install from PSGallery
  shell:
    cmd: |
      if ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted')
      {
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      }
    executable: /usr/bin/pwsh
  register: ps_allow_psgallery
  changed_when: "ps_allow_psgallery.rc != 0"

- name: Create profile.ps1 directory
  file:
    path: "{{ pwshrc_dir | dirname }}"
    state: directory

- name: Create profile.ps1 when not exist
  copy:
    content: ""
    dest: "{{ pwshrc_dir }}"
    force: no

- name: Configure powershell
  blockinfile:
    path: "{{ pwshrc_dir }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: true
    block: |
      # Set the VI mode
      Set-PSReadlineOption -EditMode vi
