---
- name: Download and Add Powershell Key to Apt-Get Keyring
  become: true
  apt:
    deb: "https://packages.microsoft.com/config/ubuntu/{{ ansible_lsb.release }}/packages-microsoft-prod.deb"
    state: present

- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
    update_cache: true
  loop:
    - xz-utils

- name: Install Powershell and .Net 6 SDK
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - powershell
    - dotnet-sdk-6.0

- name: Make sure we can install from PSGallery
  shell:
    cmd: |
      if ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted')
      {
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      }
    executable: /usr/bin/pwsh
  register: ps_allow_psgallery
  changed_when: "ps_allow_psgallery.rc != 0"

- name: Create profile.ps1 directory
  file:
    path: "{{ pwshrc_dir | dirname }}"
    state: directory

- name: Configure powershell
  blockinfile:
    marker: '# {mark} source append files'
    state: present
    path: "{{ pwshrc_dir }}"
    create: true
    backup: true
    block: |
      . '~/.config/powershell/profile_append.ps1'

- name: Make sure ps modules are installed
  shell:
    cmd: |
      if ('{{ item.name }}' -notin (Get-Module -ListAvailable | Select-Object -ExpandProperty Name))
      {
          Install-Module '{{ item.name }}' -Scope CurrentUser -AcceptLicense
      }
    executable: /usr/bin/pwsh
  register: ps_module_installed
  changed_when: "ps_module_installed.rc != 0"
  loop: "{{ ps_modules }}"
