---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - python3
    - python3-pip
    - python3-yaml

- name: Install ansible development related items
  become: true
  pip:
    executable: /usr/bin/pip3
    name: ['ansible-lint', 'molecule', 'testinfra']
    state: present

- name: Check if the environment exists
  stat:
    path: "{{ dev_condaenv }}"
  register: dev_condaenv_ret

- name: Create conda env for development of this repo
  when: not dev_condaenv_ret.stat.exists
  shell: "{{ conda_default_bin }} create -p {{ dev_condaenv }} python=3.8"

- name: Install many lsp from pip
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip install \
        'python-language-server[all]' \
        pyyaml \
        cmake-language-server \
        hdl-checker
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"
