---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - python3
    - python3-pip

- name: Install ansible development related items
  become: true
  pip:
    executable: /usr/bin/pip3
    name: ['ansible-lint', 'molecule', 'testinfra']
    state: present
