---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - python3
    - python3-pip
    - python3-yaml

- name: Check if the environment exists
  stat:
    path: "{{ dev_condaenv }}"
  register: dev_condaenv_ret

- name: Create conda env for development of this repo
  when: not dev_condaenv_ret.stat.exists
  shell: "{{ conda_default_bin }} create -p {{ dev_condaenv }} python=3.8"

- name: Install ansible dev tool
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        ansible-lint \
        lxml \
        pyqtgraph \
        docker-compose \
        requests
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"
