---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - python3
    - python3-pip
    - python3-yaml

- name: Create conda conda envs
  include_tasks: create.yml
  vars:
    envpath: "{{ dev_condaenv }}"

- name: Create conda conda envs 2
  include_tasks: create.yml
  vars:
    envpath: "{{ dev_condaenv2 }}"

- name: Install ansible dev tool
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        ansible-lint \
        lxml \
        pyqtgraph \
        docker-compose \
        more_itertools \
        python-lsp-server[all] \
        requests
  register: many_install
  failed_when: "many_install.rc != 0"
  changed_when: "many_install.rc != 0"
