---
- name: Check if the folder exists
  stat:
    path: "{{ focus_side_repos }}"
  register: focus_side_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "focus_side_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ focus_side_repos }}"
  register: git_fetch_focus_side
  changed_when: "git_fetch_focus_side.rc != 0"

- name: Get latest source code for focus_side
  git:
    repo: https://github.com/jkc-sw/focus-side.vim.git
    dest: "{{ focus_side_repos }}"
    clone: true
    version: "{{ focus_side_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_focus_side
