---
- name: Check if the folder exists
  stat:
    path: "{{ packer_repos }}"
  register: packer_repos_exists

- name: Get latest source code for packer
  when: "not packer_repos_exists.stat.exists"
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ packer_repos }}"
    clone: true
    version: "{{ packer_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_packer
