---
- name: Check vim-plug script existance
  stat:
    path: "{{ vim_plug_script_path }}"
  register: vim_plug_script_result

- name: Make sure autoload folder for vimplug exists
  file:
    path: "{{ vim_plug_script_path | dirname }}"
    state: directory

- name: If vim-plug script doesn't exist, install it
  when: not vim_plug_script_result.stat.exists
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_plug_script_path }}"
    mode: 0755

