---
- name: Make sure autoload folder for vimplug exists
  file:
    path: "{{ vim_plug_script_path | dirname }}"
    state: directory

- name: Install vim-plug installer
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    force: true
    dest: "{{ vim_plug_script_path }}"
    mode: 0755

