---
- hosts: local
  gather_facts: true
  roles:
    - ansible_dev
    - bashrc_like_a_pro
    - vim_plugin_update
    - docker_install
  pre_tasks:
    - name: Make sure some system dependencies are installed
      become: true
      package:
        name: "{{ item }}"
        state: 'present'
      with_items:
        - git
        - wget
        - tree
        - curl
        - tmux
