---
- hosts: local
  gather_facts: true
  roles:
    - doas_install
    - lttng_install
    - xmonad_wm
    - kernel_tools
    - zsh_setup
    - vim_plugin_update
    - caddy_install
    - lookatme_install
    - networking_tools
    - matlab_schemer
    # - insync_install
    - openconnect_vpn
    - p4
    - ghdl

  pre_tasks:
    - name: Make sure some system dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: 'present'
        update_cache: true
      loop:
        - git
        - wget
        - tree
        - curl
        - figlet
        - lolcat
        - smbclient
        - samba-common
        - cifs-utils
        - gdb
        - apt-transport-https
        - pv
        - nmap
        - gawk
        - xvfb
        - htop
        - openssh-server
        - net-tools
        - cppcheck
        - moreutils
        - util-linux
        - parallel
        - coreutils
        - software-properties-common
        - pdfgrep

    - name: Make sure some system dependencies are installed without Ubuntu 16.04
      become: true
      when: "ansible_lsb.release != '16.04'"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - rclone
