---
- hosts: local
  gather_facts: true
  vars:
    home_dir: "{{ ansible_env.HOME }}"
    vim_plug_script_path: "{{ home_dir + '/.local/share/nvim/site/autoload/plug.vim' }}"
    git_repos: "{{ home_dir + '/repos/neovim' }}"
    dotfiles_repos: "{{ home_dir + '/repos/dotfiles' }}"
  tasks:

    - name: See if system is reachable
      ping:
        data: "pong"

    - name: Make sure some functions are in bashrc
      blockinfile:
        path: ~/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: "{{ item }}"
      with_items:
        - |
          # Declare function to add path
          # https://unix.stackexchange.com/questions/14895/duplicate-entries-in-path-a-problem
          # Answer from: Gilles
          # answered Jun 13 '11 at 8:34
          function addThisPath() {
              case ":$PATH:" in
              *":$1:"*) :;; # already there
              *) PATH="$1:$PATH";; # or PATH="$PATH:$1"
              esac
          }
          export TERM=xterm-256color
          if [[ -d "$HOME/.vim/plugged/fzf" ]]; then
              addThisPath "$HOME/.vim/plugged/fzf/bin"
              . "$HOME/.vim/plugged/fzf/shell/completion.bash"
              . "$HOME/.vim/plugged/fzf/shell/key-bindings.bash"
          fi
          set -o vi
          if command -v fd &>/dev/null; then
              export FZF_DEFAULT_COMMAND='fd --hidden --type file --color=always'
              export FZF_DEFAULT_OPTS="--ansi"
          elif command -v fdfind &>/dev/null; then
              export FZF_DEFAULT_COMMAND='fdfind --hidden --type file --color=always'
              export FZF_DEFAULT_OPTS="--ansi"
              alias fd=fdfind
          fi
          nv () {
              if command -v nvim &>/dev/null; then
                  nvim $@
              fi
          }
          if [[ -x "$HOME/.vim/plugged/fzf/bin/fzf" ]]; then
              addThisPath "$HOME/.vim/plugged/fzf/bin"
              if [[ -d "$HOME/.vim/plugged/fzf/shell" ]]; then
                  for f in $(ls  "$HOME/.vim/plugged/fzf/shell/"*.bash); do
                      . "$f"
                  done
              fi
              alias his='eval "$(history | tac | sed -n "s/[ 0-9]\+\(.*\)/\1/p" | fzf)"'
          fi

    - name: Make sure some system dependencies are installed
      become: true
      package:
        name: "{{ item }}"
        state: 'present'
      with_items:
        - git
        - gcc
        - make
        - wget
        - curl
        - fd
        - ripgrep
        - stow
        - ninja-build
        - gettext
        - libtool
        - libtool-bin
        - autoconf
        - automake
        - cmake
        - g++
        - pkg-config
        - unzip

    - name: Get latest source code for neovim
      git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ git_repos }}"
        clone: true
        version: HEAD
        update: true
      register: git_clone_neovim

    - name: Compile and update neovim
      when: git_clone_neovim.changed
      community.general.make:
        chdir: "{{ git_repos }}"
        target: all
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo
      register: compile_neovim

    - name: Install neovim
      when: compile_neovim.changed
      community.general.make:
        chdir: "{{ git_repos }}"
        target: install
      become: true

    - name: Check vim-plug script existance
      stat:
        path: "{{ vim_plug_script_path }}"
      register: vim_plug_script_result

    - name: If vim-plug script doesn't exist, install it
      when: not vim_plug_script_result.stat.exists
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ vim_plug_script_path }}"
        mode: 0755

    - name: Get my dotfiles
      git:
        repo: https://github.com/jkc-sw/dotfiles.git
        dest: "{{ dotfiles_repos }}"
        clone: true
        version: HEAD
        update: true
      notify:
        - Stow the destination

    - name: Stow the destination
      shell:
        chdir: "{{ dotfiles_repos }}"
        cmd: stow -t {{ home_dir }} tmux -R && stow -f {{ home_dir }} nvim -R

    - name: Update neovim plugin
      shell:
        cmd: nvim -c 'PlugUpdate' -c 'qa'
      args:
        warn: false

