---
- hosts: local
  gather_facts: true
  roles:
    - xmonad_wm
    - vnc
    - kernel_tools
    - ansible_dev
    - zsh_setup
    - vim_plugin_update
    - caddy_install
    - lookatme_install
    - networking_tools
    - matlab_schemer
    # - insync_install
    - openconnect_vpn
    - p4

  pre_tasks:
    - name: Make sure some system dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: 'present'
        update_cache: true
      loop:
        - git
        - wget
        - tree
        - curl
        - figlet
        - lolcat
        - smbclient
        - samba-common
        - cifs-utils
        - gdb
        - apt-transport-https
        - pv
        - nmap
        - gawk
        - xvfb
        - htop
        - openssh-server
        - net-tools
        - cppcheck
