---
- hosts: local
  gather_facts: true
  roles:
    - ansible_dev
    - zsh_setup
    - vim_plugin_update
    - caddy_install
    - lookatme_install
    - networking_tools
    - matlab_schemer
  pre_tasks:
    - name: Make sure some system dependencies are installed
      become: true
      package:
        name: "{{ item }}"
        state: 'present'
        update_cache: true
      with_items:
        - git
        - wget
        - tree
        - curl
        - tmux
        - smbclient
        - samba-common
        - gdb
        - apt-transport-https
        - pv
        - nmap
        - gawk
        - xvfb
        - htop
        - openssh-server
        - net-tools
