---
- name: Get latest source code for doxygen
  git:
    repo: https://github.com/doxygen/doxygen.git
    dest: "{{ doxygen_repos }}"
    clone: true
    version: "{{ doxygen_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_doxygen

- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - python
    - cmake
    - flex
    - bison
    - build-essential
    - git
    - graphviz

- name: Create the build folder
  file:
    path: "{{ doxygen_repos }}/build"
    state: 'directory'

- name: Configure before running build for doxygen
  when: git_clone_doxygen.changed
  shell:
    chdir: "{{ doxygen_repos }}/build"
    cmd: |
      cmake -G "Unix Makefiles" ..

- name: Compile and update doxygen
  when: git_clone_doxygen.changed
  community.general.make:
    chdir: "{{ doxygen_repos }}/build"
    target: install
  register: doxygen_built
  become: true

