---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: absent
    name:
      - tmuxinator

- name: Check if the folder exists
  stat:
    path: "{{ tpm_repos }}"
  register: tpm_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "tpm_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ tpm_repos }}"
  register: git_fetch_tpm
  changed_when: "git_fetch_tpm.rc != 0"

- name: Get my tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tpm_repos }}"
    clone: true
    version: "{{ tpm_repo_version | default('HEAD') }}"
    update: true

- name: Update the plugin
  # get the command from here
  # https://raw.githubusercontent.com/tmux-plugins/tpm/master/docs/managing_plugins_via_cmd_line.md
  shell:
    cmd: "{{ item }}"
    executable: /bin/bash
  with_items:
    - "{{ source_shellfunc }} ; {{ tpm_install_bin }}"
    - "{{ source_shellfunc }} ; {{ tpm_update_bin }} all"
    - "{{ source_shellfunc }} ; {{ tpm_clean_bin }}"
  register: tpm_update
  failed_when: "tpm_update.rc != 0"
  changed_when: "tpm_update.rc != 0"
