---
# - name: Intsall bitwarden cli
#   community.general.homebrew:
#     path: /home/linuxbrew/.linuxbrew/bin
#     state: present
#     name:
#       - bitwarden-cli

- name: Intsall bitwarden gui and CLI
  shell:
    cmd: |
      {{ nix_env_bin }} -iA nixpkgs.bitwarden-cli nixpkgs.bitwarden
    executable: /bin/bash
  register: nix_install
  changed_when: 'nix_install.rc != 0'
  failed_when: 'nix_install.rc != 0'


# vim:et ts=2 sts=2 sw=2
