---
- name: Check if texlab is installed
  shell: command -v texlab && echo good || echo bad
  register: texlab_present
  changed_when: "'bad' in texlab_present.stdout"

- name: Check if the folder exists
  stat:
    path: "{{ texlab_repos }}"
  register: texlab_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "texlab_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ texlab_repos }}"
  register: git_fetch_texlab
  changed_when: "git_fetch_texlab.rc != 0"

- name: Get latest source code for texlab
  git:
    repo: https://github.com/latex-lsp/texlab.git
    dest: "{{ texlab_repos }}"
    clone: true
    version: "{{ texlab_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_texlab

- name: Compile and update texlab
  when: git_clone_texlab.changed or texlab_present.changed
  shell:
    cmd: "{{ cargo_default_bin }}/cargo build --release"
    chdir: "{{ texlab_repos }}"

# vim:et ts=2 sts=2 sw=2
