---
- name: Check if rust_analyzer is installed
  shell: command -v rust-analyzer && echo good || echo bad
  register: rust_analyzer_present
  changed_when: "'bad' in rust_analyzer_present.stdout"

- name: Check if the folder exists
  stat:
    path: "{{ rust_analyzer_repos }}"
  register: rust_analyzer_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "rust_analyzer_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ rust_analyzer_repos }}"
  register: git_fetch_rust_analyzer
  changed_when: "git_fetch_rust_analyzer.rc != 0"

- name: Get latest source code for rust-analyzer
  git:
    repo: https://github.com/rust-analyzer/rust-analyzer.git
    dest: "{{ rust_analyzer_repos }}"
    clone: true
    version: "{{ rustanalyzer_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_rust_analyzer

- name: Compile and update rust_analyzer
  when: git_clone_rust_analyzer.changed or rust_analyzer_present.changed
  shell:
    cmd: "{{ cargo_default_bin }}/cargo xtask install --server"
    chdir: "{{ rust_analyzer_repos }}"

