---
- name: run apt-get update
  apt:
    update_cache: yes
  become: yes
  register: network_cache_update
  failed_when: "network_cache_update.failed"
  changed_when: "network_cache_update.failed"

- name: let non root to capture traffic
  # Before installing any package, this only sets the preference for the question
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'
  become: yes

- name: Install wiresharkcli, gui and tshark
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - wireshark
    - tshark

- name: add current user to wireshark group
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: wireshark
  become: yes

- name: Install nethogs
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - nethogs

- name: Get the command path
  shell:
    cmd: 'command -v nethogs'
  register: where_is_nethogs

- name: Set the capability
  become: true
  community.general.capabilities:
    state: present
    capability: 'cap_net_admin,cap_net_raw+pe'
    path: "{{ where_is_nethogs.stdout }}"

