---
- name: Make sure the dependency is installed for luals
  become: true
  apt:
    state: 'present'
    name:
      - ninja-build

- name: Check if the folder exists
  stat:
    path: "{{ luals_repos }}"
  register: luals_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "luals_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ luals_repos }}"
  register: git_fetch_luals
  changed_when: "git_fetch_luals.rc != 0"

- name: Get latest source code for luals
  git:
    repo: https://github.com/luals/lua-language-server
    dest: "{{ luals_repos }}"
    clone: true
    version: "{{ luals_repo_version | default('HEAD') }}"
    update: true
    recursive: true
  register: git_clone_luals

- name: Build from source for luals
  when: git_clone_luals.changed
  shell:
    cmd: ./make.sh
    chdir: "{{ luals_repos }}"

