---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: 'present'
    update_cache: true
    name:
      - curl
      - xz-utils

- name: Check nix-env is installed
  shell: command -v 'nix-env' && echo good || echo bad
  register: nix_present
  changed_when: "'bad' in nix_present.stdout"

- name: Install nix
  shell:
    cmd: |
      export NIX_INSTALLER_NO_MODIFY_PROFILE=1 ; /bin/bash <(curl -L https://nixos.org/nix/install)
    executable: /bin/bash
  when: nix_present.changed
  register: nix_install

- name: Enable experimental features of nix
  lineinfile:
    path: "{{ home_dir + '/.config/nix/nix.conf' }}"
    line: "experimental-features = nix-command flakes"
    state: present
    backup: true
    create: true

- name: Update the nix config to allow unfree
  lineinfile:
    path: "{{ home_dir + '/.config/nixpkgs/config.nix' }}"
    line: "{ allowUnfree = true; }"
    state: present
    backup: true
    create: true

# vim:et ts=2 sts=2 sw=2
