---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: 'present'
    update_cache: true
    name:
      - curl
      - xz-utils

- name: Check nix is installed
  shell:
    executable: /bin/bash
    cmd: |
      [[ -d /nix/var/nix/profiles/default/bin ]] && echo good || echo bad
  register: nix_present
  changed_when: "'bad' in nix_present.stdout"

- name: Check if nix folder exist
  stat:
    path: /nix/var/nix/profiles/default/bin
  register: nix_installer_exist

- name: Default flags to pass to the nix installer. In normal linux, none
  set_fact:
    nix_installer_install_flags: ''

- name: When running nix in docker, we need to pass in additional flags
  tags:
    - nixdocker
  set_fact:
    nix_installer_install_flags: '--extra-conf "sandbox = false" --no-start-daemon'

- name: Install nix with nix-installer from determinate system when not found.
  shell:
    cmd: |
      installerArgs=( install linux --no-confirm {{ nix_installer_install_flags }} )
      # initNone=false
      # if ! command -v systemctl &>/dev/null; then
      #   initNone=true
      # elif command -v systemctl &>/dev/null && [[ "$(ps -aux | grep -v grep | grep systemd | wc -l)" -eq 0 ]]; then
      #   initNone=true
      # fi
      # if [[ "$initNone" == 'true' ]]; then
      #   installerArgs+=( --init none )
      # fi
      echo "installerArgs = ${installerArgs[*]}"
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | /bin/bash -s -- "${installerArgs[@]}"
    executable: /bin/bash
  when: not nix_installer_exist.stat.exists
  register: nix_install

- name: Enable nix experimental feature
  become: true
  lineinfile:
    dest: /etc/nix/nix.conf
    state: present
    create: true
    regexp: 'experimental-features'
    line: "experimental-features = nix-command flakes"

- name: workaround to fix nix permission issue in the profile per my user
  become: true
  file:
    path: /nix/var/nix/profiles/per-user/chenkua
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    recurse: true
    state: directory

- name: workaround to fix nix permission issue in the profile
  become: true
  file:
    path: /nix/var/nix/profiles/per-user
    mode: 'o+rw'
    recurse: true
    state: directory

# # Uninstall, not really useful
# - name: Uninstall yq
#   shell:
#     cmd: |
#       {{ nix_env_bin }} --uninstall yq
#     executable: /bin/bash
#   register: nix_install
#   changed_when: 'nix_install.rc != 0'
#   failed_when: 'nix_install.rc != 0'

- name: Update the nix config to allow unfree
  lineinfile:
    path: "{{ home_dir + '/.config/nixpkgs/config.nix' }}"
    line: "{ allowUnfree = true; }"
    state: present
    backup: true
    create: true

# Uninstall, not really useful
- name: Uninstall yq
  shell:
    cmd: |
      {{ nix_env_bin }} --uninstall yq
    executable: /bin/bash
  register: nix_install
  changed_when: 'nix_install.rc != 0'
  failed_when: 'nix_install.rc != 0'

# - name: Install nixpkgs.valgrind nixpkgs.kcachegrind
#   shell:
#     cmd: |
#       {{ nix_env_bin }} -f '<nixpkgs>' -iA valgrind kcachegrind
#     executable: /bin/bash
#   register: nix_install
#   changed_when: 'nix_install.rc != 0'
#   failed_when: 'nix_install.rc != 0'
#
# - name: Install dvc, manipulating large file text pointer like git-lfs does
#   shell:
#     cmd: |
#       {{ nix_env_bin }} -f '<nixpkgs>' -iA dvc
#     executable: /bin/bash
#   register: nix_install
#   changed_when: 'nix_install.rc != 0'
#   failed_when: 'nix_install.rc != 0'

# vim:et ts=2 sts=2 sw=2
