---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - stow
    - xclip
    - git

- name: Get if dotfile repos is there
  stat:
    path: "{{ dotfiles_repos }}"
  register: dotfiles_repos_ret

- name: Get my dotfiles
  when: (not dotfiles_repos_ret.stat.exists) or (update_dotfile | default(false))
  git:
    repo: https://github.com/jkc-sw/dotfiles.git
    dest: "{{ dotfiles_repos }}"
    clone: true
    version: HEAD
    update: true

- name: Setup the git config
  community.general.git_config:
    state: present
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: url.'ssh://git@github.com/'.pushInsteadOf
      value: https://github.com/
    - name: core.editor
      value: nvim

- name: Stow the destination
  shell:
    cmd: "stow -t '{{ home_dir }}' -R {{ item }}"
    chdir: "{{ dotfiles_repos }}"
    executable: /bin/bash
  register: restow
  with_items: "{{ targets }}"
  changed_when: "restow.rc != 0"

