---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - stow

- name: Get my dotfiles
  git:
    repo: https://github.com/jkc-sw/dotfiles.git
    dest: "{{ dotfiles_repos }}"
    clone: true
    version: HEAD
    update: true
  register: git_clone_dotfiles

- name: Stow the destination
  when: git_clone_dotfiles.changed
  shell:
    cmd: |
      stow -t '{{ home_dir }}' -R tmux
      stow -t '{{ home_dir }}' -R nvim
    chdir: "{{ dotfiles_repos }}"
    executable: /bin/bash

