---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - stow
    - xclip
    - git

- name: Get if dotfile repos is there
  stat:
    path: "{{ dotfiles_repos }}"
  register: dotfiles_repos_ret

- name: Check if the folder exists
  stat:
    path: "{{ dotfiles_repos }}"
  register: dotfiles_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "dotfiles_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ dotfiles_repos }}"
  register: git_fetch_dotfiles
  changed_when: "git_fetch_dotfiles.rc != 0"

- name: Get my dotfiles
  when: (not dotfiles_repos_ret.stat.exists) or (update_dotfile | default(false))
  git:
    repo: https://github.com/jkc-sw/dotfiles.git
    dest: "{{ dotfiles_repos }}"
    clone: true
    version: HEAD
    update: true

- name: Remove old config
  file:
    path: "{{ home_dir + '/.gitconfig' }}"
    state: 'absent'

- name: Stow the destination
  shell:
    cmd: "stow -t '{{ home_dir }}' -R {{ item }}"
    chdir: "{{ dotfiles_repos }}"
    executable: /bin/bash
  register: restow
  with_items: "{{ stow_targets }}"
  changed_when: "restow.rc != 0"

