---
- name: Get my dotfiles
  git:
    repo: https://github.com/jkc-sw/dotfiles.git
    dest: "{{ dotfiles_repos }}"
    clone: true
    version: HEAD
    update: true

- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - stow

- name: Stow the destination
  shell:
    cmd: "stow -t '{{ home_dir }}' -R {{ item }}"
    chdir: "{{ dotfiles_repos }}"
    executable: /bin/bash
  register: restow
  with_items: "{{ targets }}"
  changed_when: "restow.rc != 0"

