---
- name: Get my dotfiles
  git:
    repo: https://github.com/jkc-sw/dotfiles.git
    dest: "{{ dotfiles_repos }}"
    clone: true
    version: HEAD
    update: true

- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - stow

- name: Stow the destination
  shell:
    cmd: |
      stow -t '{{ home_dir }}' -R tmux && \
      stow -t '{{ home_dir }}' -R starship && \
      stow -t '{{ home_dir }}' -R bashrc && \
      stow -t '{{ home_dir }}' -R shellfunc && \
      stow -t '{{ home_dir }}' -R zshrc && \
      stow -t '{{ home_dir }}' -R neovim
    chdir: "{{ dotfiles_repos }}"
    executable: /bin/bash
  register: restow
  changed_when: "restow.rc != 0"

