---
- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - xserver-xorg
    - libpangocairo-1.0-0

- name: Install first
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        mypy \
        cffi \
        xdg \
        dbus_next \
        xcffib
  register: qtile_install
  failed_when: "qtile_install.rc != 0"
  changed_when: "qtile_install.rc != 0"

- name: Install then
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        --no-cache-dir \
        cairocffi
  register: qtile_install
  failed_when: "qtile_install.rc != 0"
  changed_when: "qtile_install.rc != 0"

- name: Check if the folder exists
  stat:
    path: "{{ qtile_repos }}"
  register: qtile_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "qtile_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ qtile_repos }}"
  register: git_fetch_repo
  changed_when: "git_fetch_repo.rc != 0"

- name: Get latest source code for
  git:
    repo: "https://github.com/qtile/qtile"
    dest: "{{ qtile_repos }}"
    clone: true
    version: "{{ qtile_repo_version | default('HEAD') }}"
    update: true

- name: Install qtile
  shell:
    chdir: "{{ qtile_repos }}"
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        -e .
  register: qtile_install
  failed_when: "qtile_install.rc != 0"
  changed_when: "qtile_install.rc != 0"

- name: Create session file
  become: true
  template:
    mode: '755'
    src: qtile-session.j2
    dest: /usr/bin/qtile-session

- name: Create desktop file
  become: true
  template:
    src: qtile.desktop.j2
    dest: /usr/share/xsessions/qtile.desktop

# vim:et ts=2 sts=2 sw=2
