---
- name: Add ppa for qt4 on Ubuntu 20
  when: "ansible_lsb.release == '20.04'"
  become: true
  apt_repository:
    repo: ppa:rock-core/qt4
    state: present
    update_cache: true

- name: Add ppa for qt4 on Ubuntu 22
  when: "ansible_lsb.release == '22.04'"
  become: true
  apt_repository:
    repo: ppa:ubuntuhandbook1/ppa
    state: present
    update_cache: true

- name: Install qt4
  when: "ansible_lsb.release != '24.04'"
  become: true
  apt:
    name: ['libqtcore4', 'libqtgui4']
    state: present

# vim:et ts=2 sts=2 sw=2
