---
- name: Install Lookatme
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        --user \
        Pygments \
        termdown \
        lookatme
  register: lookatmeinstall
  failed_when: "lookatmeinstall.rc != 0"
  changed_when: "lookatmeinstall.rc != 0"

- name: Install pandoc for Ubuntu 18 and up
  when: fast | default(true)
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    state: present
    name:
      - pandoc

