---
# - name: Intsall yt-dlp
#   community.general.homebrew:
#     path: /home/linuxbrew/.linuxbrew/bin
#     state: present
#     name:
#       - yt-dlp

- name: Intsall yt-dlp
  shell:
    cmd: |
      {{ nix_env_bin }} -iA nixpkgs.yt-dlp-light
    executable: /bin/bash
  register: ytdlp_install
  changed_when: 'ytdlp_install.rc != 0'
  failed_when: 'ytdlp_install.rc != 0'

# vim:et ts=2 sts=2 sw=2
