---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - libssl-dev

- name: Install all those fancy variables
  shell:
    cmd: "{{ cargo_default_bin }}/cargo install {{ item.crate }}"
  with_items: "{{ crates }}"
  register: cargo_install
  failed_when: "cargo_install.rc != 0"
  changed_when: "cargo_install.rc != 0"

- name: Initialize starship on bash
  lineinfile:
    path: "{{ bashrc_path }}"
    line: eval "$(starship init bash)"
    state: present
    backup: true

- name: Initialize starship on powershell
  lineinfile:
    path: "{{ pwshrc_dir }}"
    line: Invoke-Expression (& starship init powershell)
    state: present
    backup: true
