---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: 'present'
    name:
      - libssl-dev
      - pkg-config

- name: Install many rust tool with brew
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    state: present
    name:
      - fd
      - rg
      - bat
      - starship
      - dust
      - exa
      - tokei
      - procs
      - sd
      - zoxide

# - name: Install all those fancy variables
#   shell:
#     cmd: "{{ cargo_default_bin }}/cargo install {{ item.crate }}"
#   with_items: "{{ crates }}"
#   register: cargo_install
#   failed_when: "cargo_install.rc != 0"
#   changed_when: "cargo_install.rc != 0"

