---
home_dir: "{{ ansible_env.HOME }}"
conda_install_dir: "{{ home_dir + '/miniconda3' }}"
conda_default_bin: "{{ conda_install_dir + '/bin/conda' }}"
conda_installer_path: "/tmp/Miniconda3-latest-Linux-x86_64.sh"

