---
- name: Add lttng repo
  become: true
  apt_repository:
    repo: ppa:lttng/stable-2.12
    state: present
    update_cache: true

- name: Install babeltrace2
  become: true
  apt:
    name: ['babeltrace2']
    state: present

# vim:et ts=2 sts=2 sw=2
