---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    state: 'present'
    update_cache: true
    name:
      - curl
      - xz-utils

- name: Check nix-env is installed
  shell: command -v 'nix-env' && echo good || echo bad
  register: nix_present
  changed_when: "'bad' in nix_present.stdout"

- name: Install nix
  shell:
    cmd: |
      export NIX_INSTALLER_NO_MODIFY_PROFILE=1 ; /bin/bash <(curl -L https://nixos.org/nix/install)
    executable: /bin/bash
  when: nix_present.changed
  register: nix_install

# # template to use for the nix install
# - name: Install something with nix for testing
#   shell:
#     cmd: |
#       {{ nix_env_bin }} -iA nixpkgs.lua5_4
#     executable: /bin/bash
#   register: nix_install
#   changed_when: 'nix_install.rc != 0'
#   failed_when: 'nix_install.rc != 0'

# vim:et ts=2 sts=2 sw=2
