---
- name: Update dotfiles
  tags:
    - dotfiles
  set_fact:
    update_dotfile: true

- name: Update gui
  tags:
    - gui
  set_fact:
    gui: true

- name: Skip the common settings for development - default is not skipping
  set_fact:
    skip_common_settings: false

- name: Skip the common settings for development
  tags:
    - skipcs
  set_fact:
    skip_common_settings: true

- name: Install llvm without building - Default build
  set_fact:
    fast: false

- name: Install llvm without building
  tags:
    - fast
  set_fact:
    fast: true

- name: Common settings
  when: not skip_common_settings | default(true)
  block:

  - name: Make sure these are not installed because of vulnerabilities
    become: true
    apt:
      state: 'absent'
      update_cache: true
      name:
        - cups-browsed

  - name: Make sure some system dependencies are installed
    become: true
    apt:
      state: 'present'
      update_cache: true
      name:
        - apt-transport-https
        - cifs-utils
        - coreutils
        - curl
        - exfat-fuse
        - git
        - iputils-ping
        - libxml2-utils
        - moreutils
        - net-tools
        - netdiscover
        - openssh-server
        - pass
        - samba-common
        - smbclient
        - software-properties-common
        - util-linux

  - name: Make sure some system dependencies are installed
    become: true
    tags:
      - rare
    apt:
      state: 'present'
      update_cache: true
      name:
        - gdb
        - pv
        - nmap
        - gawk
        - xvfb
        - htop
        - cppcheck
        - autocutsel
        - iftop
        - parallel
        - pdfgrep
        - gnupg
        - faketime
        - qtpass
        - expect
        - gv
        - mupdf
        - tikzit # Can be from source in the future
        - ncdu
        - jq
        - texinfo
        - gcc-multilib
        - wiggle
        - iperf3
        - osslsigncode
        - tldr
        - sshpass
        - nvme-cli

  - name: Ubuntu 20 specific
    become: true
    when: "ansible_lsb.release == '20.04'"
    apt:
      state: present
      name:
        - exfat-utils

  - name: Not Ubuntu 20 specific
    become: true
    when: "ansible_lsb.release != '20.04'"
    apt:
      state: present
      name:
        - exfatprogs

  - name: Other not on Ubuntu 24 or had a different name before Ubuntu 24
    become: true
    when: "ansible_lsb.release != '24.04'"
    tags:
      - extra
    apt:
      state: present
      name:
        - libtinfo5
        - libncurses5
        - lsb

  - name: Ubuntu 24 specific
    become: true
    when: "ansible_lsb.release == '24.04'"
    tags:
      - extra
    apt:
      state: present
      name:
        - libtinfo6
        - libncurses6

  # - name: Install the xmonad (Don't use this, unless I want to setup the xmonad project from source)
  #   shell:
  #     cmd: |
  #       export BOOTSTRAP_HASKELL_NONINTERACTIVE=1 # any nonzero value for noninteractive installation
  #       export BOOTSTRAP_HASKELL_NO_UPGRADE=0 # any nonzero value to not trigger the upgrade
  #       export GHCUP_USE_XDG_DIRS=1 # any nonzero value to respect The XDG Base Directory Specification
  #       export BOOTSTRAP_HASKELL_VERBOSE=1 # any nonzero value for more verbose installation
  #       export BOOTSTRAP_HASKELL_INSTALL_STACK=1 # whether to install latest stack
  #       export BOOTSTRAP_HASKELL_INSTALL_HLS=1 # whether to install latest hls
  #       export BOOTSTRAP_HASKELL_ADJUST_BASHRC=  # whether to adjust PATH in bashrc (prepend)
  #       curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  #   register: ghcup_install
  #   failed_when: "ghcup_install.rc != 0"
  #   changed_when: "ghcup_install.rc != 0"

# vim:et ts=2 sts=2 sw=2
