---
- name: Download and Add Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://apt.netmaker.org/gpg.key"
    state: present

- name: Add Repository into /etc/apt/sources.list
  become: true
  apt_repository:
    repo: "deb https:apt.netmaker.org stable main"
    state: present
    update_cache: true

- name: Install netclient
  become: true
  apt:
    name: netclient
    state: present

# # Since this only works for the real machine, comment out here
# - name: Make sure the service is running
#   systemd:
#     name: zerotier-one
#     state: started
#     enabled: yes

# vim:et ts=2 sts=2 sw=2
