---
- name: Check conda is installed
  shell: command -v '{{ conda_default_bin }}' && echo good || echo bad
  register: conda_present
  changed_when: "'bad' in conda_present.stdout"

- name: Get the installer
  when: conda_present.changed
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{ conda_installer_path }}"

- name: Install conda
  shell: "/bin/bash {{ conda_installer_path }} -b -p {{ conda_install_dir }}"
  when: conda_present.changed
  register: conda_install
  args:
    warn: false

- name: Init the shells
  shell:
    executable: /bin/bash
    cmd: |
      {{ conda_default_bin }} init bash && \
      {{ conda_default_bin }} init powershell && \
      {{ conda_default_bin }} init zsh
  register: conda_init_shells
  changed_when: "conda_init_shells.rc != 0"
  failed_when: "conda_init_shells.rc != 0"

- name: Do not auto activate base
  shell: "{{ conda_default_bin }} config --set auto_activate_base false"
  register: conda_setter
  changed_when: "conda_setter.rc != 0"
  failed_when: "conda_setter.rc != 0"

- name: Do not show the env name
  shell: "{{ conda_default_bin }} config --set changeps1 false"
  register: conda_setter
  changed_when: "conda_setter.rc != 0"
  failed_when: "conda_setter.rc != 0"

- name: Remove installer
  file:
    path: "{{ conda_installer_path }}"
    state: 'absent'
