---
- name: Check if starship is installed
  shell: command -v starship && echo good || echo bad
  register: starship_present
  changed_when: "'bad' in starship_present.stdout"

- name: Get latest source code for starship/starship-find
  git:
    repo: https://github.com/starship/starship.git
    dest: "{{ starship_repos }}"
    clone: true
    version: HEAD
    update: true
  register: git_clone_starship

- name: Make sure some system dependencies are installed
  when: git_clone_starship.changed or starship_present.changed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - libssl-dev

- name: Compile and update starship
  when: git_clone_starship.changed or starship_present.changed
  shell:
    cmd: "{{ cargo_default_bin }}/cargo install --locked --path ."
    chdir: "{{ starship_repos }}"

- name: Add starship to bashrc
  lineinfile:
    path: "{{ bashrc_path }}"
    line: eval "$(starship init bash)"
    state: present
    backup: true
