---
- name: Check if the nvm is installed
  shell:
    cmd: "{{ source_bashrc }} && command -v nvm && echo good || echo bad"
    executable: /bin/bash
  register: nvm_present
  changed_when: "'bad' in nvm_present.stdout"

- name: Get the installer
  when: nvm_present.changed
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh
    dest: "{{ nvm_install_script }}"

- name: Install nvm
  shell: "bash {{ nvm_install_script }}"
  when: nvm_present.changed
  register: nvm_install
  args:
    warn: false

- name: Remove installer
  when: nvm_install.changed
  file:
    path: "{{ nvm_install_script }}"
    state: 'absent'

# # Do not do this, as it makes every sourcing slow
# - name: Add the latest node with line to source in bashrc
#   when: nvm_install.changed
#   lineinfile:
#     path: "{{ bashrc_path }}"
#     state: 'present'
#     line: "nvm use node"
#     insertafter: 'export NVM_DIR="$HOME/.nvm"'

- name: Check if the node is installed
  shell:
    cmd: "{{ use_node }} && command -v node && echo good || echo bad"
    executable: /bin/bash
  register: node_present
  changed_when: "'bad' in node_present.stdout"

- name: Install latest node
  when: node_present.changed
  shell:
    cmd: "{{ nvm_bin }} install node"
    executable: /bin/bash

- name: Check if the yarn is installed
  shell: command -v yarn && echo good || echo bad
  register: yarn_present
  changed_when: "'bad' in yarn_present.stdout"

- name: Download and Add yarn Key to Apt-Get Keyring
  when: yarn_present.changed
  become: true
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present

- name: Add yarn Repository into /etc/apt/sources.list - Bionic
  when: yarn_present.changed
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install yarn
  when: yarn_present.changed
  become: true
  apt:
    name: 'yarn'
    state: present
    install_recommends: false
