---
- name: Check if the nvm is installed
  shell:
    cmd: "bash -i -c '{{ source_bashrc }} && command -v nvm && echo good || echo bad'"
    executable: /bin/bash
  register: nvm_present
  changed_when: "'bad' in nvm_present.stdout"

- name: Get the installer
  when: nvm_present.changed
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh
    dest: "{{ nvm_install_script }}"

- name: Install nvm
  shell:
    cmd: "/bin/bash {{ nvm_install_script }}"
  when: nvm_present.changed
  register: nvm_install
  args:
    warn: false

- name: Remove installer
  file:
    path: "{{ nvm_install_script }}"
    state: 'absent'

- name: Install latest node
  when: nvm_install.changed
  shell:
    cmd: "bash -i -c '{{ nvm_bin }} install node'"
    executable: /bin/bash

- name: Download and Add yarn Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present

- name: Add yarn Repository into /etc/apt/sources.list - Bionic
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Install yarn
  become: true
  apt:
    name: 'yarn'
    state: present
    install_recommends: false
