---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - git
    - curl
    - zsh
    - libcap-ng-dev
    - netcat
    - minicom

- name: Remove the old installer
  file:
    path: "{{ omz_installer }}"
    state: absent

- name: Remove the old repo
  file:
    path: "{{ omz_installer }}"
    state: absent

- name: Ensure the antigen installer folder exist
  file:
    path: "{{ antigen_installer | dirname }}"
    state: directory

- name: Download antigen installer
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
    force: true
    dest: "{{ antigen_installer }}"
    mode: 0755

- name: Change the default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
    state: present
    append: yes
    groups: 'dialout'

- name: Add zshrc append
  lineinfile:
    path: "{{ zshrc_path }}"
    line: ". '{{ zshrc_append_path }}'"
    state: present
    backup: true
    create: true
    insertbefore: BOF

- name: Remove old custom plugins
  file:
    path: "{{ item.dst }}"
    state: absent
  with_items: "{{ zsh_custom_plugs }}"

- name: Remove old custom plugin folder
  file:
    path: "{{ omz_custom_dir }}"
    state: absent
