---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - git
    - curl
    - zsh

- name: Check the omz repo exist
  stat:
    path: "{{ omz_repos }}"
  register: omz_repo_present

- name: Get the installer
  when: not omz_repo_present.stat.exists
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ omz_installer }}"
  register: omz_installer_download

- name: Install omz
  when: omz_installer_download.changed
  shell:
    cmd: "ZSH='{{ omz_repos }}' /bin/bash {{ omz_installer }} --unattended --keep-zshrc"
    executable: /bin/bash

- name: Change the default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Remove installer
  when: omz_installer_download.changed
  file:
    path: "{{ omz_installer }}"
    state: 'absent'

- name: Add zshrc append
  lineinfile:
    path: "{{ zshrc_path }}"
    line: ". '{{ zshrc_append_path }}'"
    state: present
    backup: true
    create: true
    insertbefore: BOF

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_autosuggestions_repos }}"
    clone: true
    version: HEAD
    update: true

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_syntax_highlight_repos }}"
    clone: true
    version: HEAD
    update: true
