---
- name: Update neovim plugin
  shell:
    cmd: nvim -c 'PlugInstall' -c 'PlugClean!' -c 'PlugUpdate' -c 'qa'
  args:
    warn: false
  register: update_nvim_plugin
  changed_when: update_nvim_plugin.rc != 0

