---
- name: Update neovim plugin
  shell:
    cmd: ANSIBLE_UPDATE=1 nvim -c 'PlugInstall|PlugClean!|PlugUpdate|qa'
  args:
    warn: false
  register: update_nvim_plugin
  changed_when: update_nvim_plugin.rc != 0

