---
- name: Install Lookatme
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        Pygments \
        termdown \
        lookatme
  register: lookatmeinstall
  failed_when: "lookatmeinstall.rc != 0"
  changed_when: "lookatmeinstall.rc != 0"

- name: Install Pandoc
  shell:
    cmd: |
      {{ conda_bin_fullpath }} install -p {{ dev_condaenv }} pandoc
  register: pandoc
  failed_when: "pandoc.rc != 0"
  changed_when: "pandoc.rc != 0"
