---
- name: Install LSP dependencies
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  register: dep_install
  with_items:
    - clangd-10
    - unzip
    - clang-10

- name: Make sure clangd is properly symlinked
  when: dep_install.changed
  become: true
  shell:
    executable: /bin/bash
    cmd: |
      [[ -e "{{ clangd_ln_path }}" ]] && rm "{{ clangd_ln_path }}"
      ln -s "{{ clangd_exe_path}}" "{{ clangd_ln_path }}"
      [[ -e "{{ clang_ln_path }}" ]] && rm "{{ clang_ln_path }}"
      ln -s "{{ clang_exe_path}}" "{{ clang_ln_path }}"

- name: Check if luacheck is installed
  shell: command -v luacheck && echo good || echo bad
  register: luacheck_present
  changed_when: "'bad' in luacheck_present.stdout"

- name: Install luacheck if not installed
  become: true
  shell: luarocks install luacheck
  when: luacheck_present.changed

