---
- name: Install LSP dependencies for 18 and above
  become: true
  when: "ansible_lsb.release != '16.04'"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - shellcheck

- name: Check if luacheck is installed
  shell: command -v luacheck && echo good || echo bad
  register: luacheck_present
  changed_when: "'bad' in luacheck_present.stdout"

- name: Install luacheck if not installed
  become: true
  shell: luarocks install luacheck
  when: luacheck_present.changed

- name: Get the npm path
  shell:
    executable: /bin/bash
    cmd: |
       {{ source_shellfunc }} && which npm
  register: which_npm
  failed_when: "which_npm.rc != 0"
  changed_when: "which_npm.rc != 0"

- name: Install many lsps
  # use environment workaround here: https://github.com/ansible/ansible/issues/55289
  npm:
    global: true
    name: "{{ item }}"
    state: present
    # executable: "{{ which_npm.stdout }}"
  with_items:
    - typescript
    - typescript-language-server
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - bash-language-server
    - vscode-langservers-extracted
    - pyright
  environment:
    PATH: "{{ which_npm.stdout | dirname }}:{{ ansible_env.PATH }}"

- name: Install many lsp from pip
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        'python-lsp-server[all]' \
        pyyaml \
        cmake-language-server \
        hdl-checker
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"

- name: Cleanup some pkgs
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        uninstall -y \
        hdl-checker
  register: pipuninstall
  failed_when: "pipuninstall.rc != 0"
  changed_when: "pipuninstall.rc != 0"

- name: Install many lsp from pip
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        'python-lsp-server[all]' \
        pyyaml \
        cmake-language-server \
        hdl-checker
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"

- name: Install many lsp from pip 2
  shell:
    cmd: |
      {{ dev_condaenv2 }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        hdl-checker
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"

- name: Install luals for the correct distro
  include_tasks: luals.yml
  when: "ansible_lsb.release == '18.04' or ansible_lsb.release == '20.04'"
