---
- name: Install LSP dependencies for 20
  include_tasks: others.yml
  when: "ansible_lsb.release == '20.04'"
  vars:
    clangd_name: 'clangd-10'
    clang_name: 'clang-10'
    pkgs:
      - unzip
      - clangd-10
      - clang-10

- name: Install LSP dependencies for 18
  include_tasks: others.yml
  when: "ansible_lsb.release == '18.04'"
  vars:
    clangd_name: 'clangd-10'
    clang_name: 'clang-10'
    pkgs:
      - unzip
      - clangd-10
      - clang-10

- name: Install LSP dependencies for 16
  include_tasks: others.yml
  when: "ansible_lsb.release == '16.04'"
  vars:
    clangd_name: 'clangd-8'
    clang_name: 'clang-8'
    pkgs:
      - unzip
      - clang-tools-8

- name: Install LSP dependencies for 18 and above
  become: true
  when: "ansible_lsb.release != '16.04'"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - shellcheck

# # This is tricky to get right, just forget it for now. Currently, clangd cannot find the headers for the std++ lib
# - name: Check if clangd is installed
#   shell: command -v clangd && echo good || echo bad
#   register: clangd_present
#   changed_when: "'bad' in clangd_present.stdout"
#
# - name: install the clangd from the source
#   when: clangd_present.changed
#   get_url:
#     url: 'https://github.com/clangd/clangd/releases/download/12.0.0/clangd-linux-12.0.0.zip'
#     dest: /tmp/clangd-linux-12.0.0.zip
#
# - name: Extract the clangd bin
#   when: clangd_present.changed
#   become: true
#   unarchive:
#     remote_src: true
#     src: /tmp/clangd-linux-12.0.0.zip
#     dest: "/tmp"
#
# - name: Copy clangd
#   when: clangd_present.changed
#   become: true
#   copy:
#     remote_src: true
#     src: "/tmp/clangd_12.0.0/bin/clangd"
#     dest: "/usr/local/bin"
#     mode: 0755
#
# - name: Copy clangd include
#   # when: clangd_present.changed
#   become: true
#   copy:
#     remote_src: true
#     src: "/tmp/clangd_12.0.0/lib/clang"
#     dest: "/usr/local/include"

- name: Check if luacheck is installed
  shell: command -v luacheck && echo good || echo bad
  register: luacheck_present
  changed_when: "'bad' in luacheck_present.stdout"

- name: Install luacheck if not installed
  become: true
  shell: luarocks install luacheck
  when: luacheck_present.changed

- name: Get the npm path
  shell:
    executable: /bin/bash
    cmd: |
       {{ source_shellfunc }} && which npm
  register: which_npm
  failed_when: "which_npm.rc != 0"
  changed_when: "which_npm.rc != 0"

- name: Install many lsps
  # use environment workaround here: https://github.com/ansible/ansible/issues/55289
  npm:
    global: true
    name: "{{ item }}"
    state: present
    # executable: "{{ which_npm.stdout }}"
  with_items:
    - typescript
    - typescript-language-server
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - bash-language-server
    - vscode-json-languageserver
    - pyright
  environment:
    PATH: "{{ which_npm.stdout | dirname }}:{{ ansible_env.PATH }}"

- name: Install many lsp from pip
  shell:
    cmd: |
      {{ dev_condaenv }}/bin/python -m pip \
        --disable-pip-version-check \
        --no-python-version-warning \
        install \
        'python-lsp-server[all]' \
        pyyaml \
        cmake-language-server \
        hdl-checker
  register: pipinstall
  failed_when: "pipinstall.rc != 0"
  changed_when: "pipinstall.rc != 0"

- name: Install luals for the correct distro
  include_tasks: luals.yml
  when: "ansible_lsb.release == '18.04' or ansible_lsb.release == '20.04'"
