---
- name: Install LSP dependencies
  become: true
  apt:
    name: "{{ pkgs }}"
    state: 'present'
  register: dep_install

- name: Make sure clangd is properly symlinked
  become: true
  file:
    path: "{{ clangd_ln_path }}"
    src: "{{ clangd_exe_path }}"
    state: link

- name: Make sure clang is properly symlinked
  become: true
  file:
    path: "{{ clang_ln_path }}"
    src: "{{ clang_exe_path }}"
    state: link

