---
- name: Check if kitty is installed
  shell: command -v kitty && echo good || echo bad
  register: kitty_present
  changed_when: "'bad' in kitty_present.stdout"

- name: Check if the folder exists
  stat:
    path: "{{ kitty_repos }}"
  register: kitty_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "kitty_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ kitty_repos }}"
  register: git_fetch_kitty
  changed_when: "git_fetch_kitty.rc != 0"

- name: Get latest source code for kitty
  git:
    repo: https://github.com/kovidgoyal/kitty.git
    dest: "{{ kitty_repos }}"
    clone: true
    version: "{{ kitty_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_kitty

- name: Make sure some system dependencies are installed
  become: true
  when: git_clone_kitty.changed or kitty_present.changed
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - libfontconfig
    - uuid
    - libgl1-mesa-dev
    - libxi-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxcb-xkb-dev
    - libdbus-1-dev
    - libxkbcommon-dev
    - libharfbuzz-dev
    - libpng-dev
    - liblcms2-dev
    - libfontconfig-dev
    - libxkbcommon-x11-dev
    - libcanberra-dev
    - uuid-dev
    - pkg-config
    - python3
    - python3-dev

- name: Compile, update and install kitty
  when: git_clone_kitty.changed or kitty_present.changed
  become: true
  community.general.make:
    chdir: "{{ kitty_repos }}"
  register: compile_kitty

- name: Make sure local bin exist
  file:
    path: "{{ local_bin }}"
    state: directory

- name: Symlink the kitty bin
  file:
    path: "{{ kitty_bin_linked }}"
    src: "{{ kitty_bin }}"
    state: link

