---
- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Download and Add docker Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker Repository into /etc/apt/sources.list
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install docker
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    append: true
    groups: 'docker'
