---
- name: Get latest source code for kinesisadv360pro
  git:
    repo: https://github.com/jkc-sw/Adv360-Pro-ZMK.git
    dest: "{{ kinesisadv360pro_repos }}"
    clone: true
    version: "{{ kinesisadv360pro_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_kinesisadv360pro

# vim:et ts=2 sts=2 sw=2
