---
- name: Install the TurboVNC server
  become: true
  apt:
    deb: "https://sourceforge.net/projects/turbovnc/files/{{ turbovnc_deb_version }}/turbovnc_{{ turbovnc_deb_version }}_amd64.deb/download"
    state: 'present'

# - name: Uninstall the TurboVNC server
#   become: true
#   apt:
#     name: 'turbovnc'
#     state: 'absent'

- name: Remove the tigervnc server
  become: true
  apt:
    name: 'tigervnc-standalone-server'
    state: 'absent'
