---
- name: Download and Add vagrant packer Key to Apt-Get Keyring
  become: true
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present

- name: Add vagrant packer Repository into /etc/apt/sources.list
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
    state: present

- name: Install vagrant packer
  become: true
  apt:
    name:
      - bridge-utils
      - curl
      - dnsmasq
      - freerdp2-x11
      - git
      - jq
      - libc6-dev
      - libguestfs-tools
      - libosinfo-bin
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-dev
      - python3-winrm
      - qemu-kvm
      - qemu-utils
      - remmina
      - spice-client-gtk
      - sshpass
      - unzip
      - virt-manager
      - virt-top
      - virtinst
      - virtualbox
      - wget
      - xorriso
      - packer
      - vagrant
    state: present
    install_recommends: false

# - name: Install python310Packages.pywinrm
#   shell:
#     cmd: |
#       {{ nix_env_bin }} -iA nixpkgs.python310Packages.pywinrm
#     executable: /bin/bash
#   register: nix_install
#   changed_when: 'nix_install.rc != 0'
#   failed_when: 'nix_install.rc != 0'


# vim:et ts=2 sts=2 sw=2
