---
- name: Build openconnect for Ubuntu 18 and up
  when: "(not fast | default(false)) and ansible_lsb.release != '24.04'"
  include_tasks: other.yml

- name: Install openconnect for Ubuntu 18 and up
  when: fast | default(true)
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    state: present
    name:
      - openconnect

- name: Make sure vpnc folder exist for the vpn script
  become: true
  file:
    path: "/etc/vpnc"
    state: directory

- name: Get the vpnc script
  become: true
  get_url:
    url: 'http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain/HEAD:/vpnc-script'
    dest: '/etc/vpnc/vpnc-script'
    mode: 0755

- name: Allow openconnect to run with sudo
  become: true
  lineinfile:
    dest: /etc/sudoers.d/openconnect
    state: present
    create: true
    regexp: 'openconnect'
    line: "{{ ansible_user_id }} ALL = (root) NOPASSWD: /usr/local/sbin/openconnect"
    validate: visudo -cf %s
