---
- name: Check if nvim is installed
  shell: command -v nvim && echo good || echo bad
  register: nvim_present
  changed_when: "'bad' in nvim_present.stdout"

- name: Get latest source code for neovim
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ nvim_repos }}"
    clone: true
    version: dc14b1468afeb53c9ca0a734a2035cc54b5e1d94
    update: "{{ update_all_repos | default(false) }}"
  register: git_clone_neovim

- name: Make sure some system dependencies are installed
  become: true
  when: git_clone_neovim.changed or nvim_present.changed
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip

- name: Compile, update and install neovim
  when: git_clone_neovim.changed or nvim_present.changed
  become: true
  community.general.make:
    chdir: "{{ nvim_repos }}"
    target: install
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  register: compile_neovim
