---
- name: Check if nvim is installed
  shell: command -v nvim && echo good || echo bad
  register: nvim_present
  changed_when: "'bad' in nvim_present.stdout"

- name: Check if the folder exists
  stat:
    path: "{{ nvim_repos }}"
  register: nvim_repos_exists

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  when: "nvim_repos_exists.stat.exists"
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ nvim_repos }}"
  register: git_fetch_nvim
  changed_when: "git_fetch_nvim.rc != 0"

- name: Get latest source code for neovim
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ nvim_repos }}"
    clone: true
    version: "{{ neovim_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_neovim

- name: Make sure some system dependencies are installed
  become: true
  when: git_clone_neovim.changed or nvim_present.changed
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip

- name: Compile, update and install neovim
  when: git_clone_neovim.changed or nvim_present.changed
  become: true
  community.general.make:
    chdir: "{{ nvim_repos }}"
    target: install
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  register: compile_neovim
