---
home_dir: "{{ ansible_env.HOME }}"
zshrc_path: "{{ home_dir + '/.zshrc' }}"
zshrc_append_path: "{{ home_dir + '/.zshrc_append' }}"
omz_installer: "/tmp/omz_install.sh"
omz_repos: "{{ home_dir + '/repos/oh-my-zsh' }}"
omz_custom_dir: "{{ home_dir + '/.zsh_custom_plugins/plugins' }}"
zsh_autosuggestions_repos: "{{ omz_custom_dir + '/zsh-autosuggestions' }}"
zsh_syntax_highlight_repos: "{{ omz_custom_dir + '/zsh-syntax-highlighting' }}"
