---
home_dir: "{{ ansible_env.HOME }}"
zshrc_path: "{{ home_dir + '/.zshrc' }}"
zshrc_append_path: "{{ home_dir + '/.zshrc_append' }}"
omz_installer: "/tmp/omz_install.sh"
omz_repos: "{{ home_dir + '/repos/oh-my-zsh' }}"
omz_custom_dir: "{{ home_dir + '/.zsh_custom_plugins/plugins' }}"
zsh_custom_plugs:
  - url: 'https://github.com/zsh-users/zsh-autosuggestions'
    dst: "{{ omz_custom_dir + '/zsh-autosuggestions' }}"
  - url: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dst: "{{ omz_custom_dir + '/zsh-syntax-highlighting' }}"
  - url: 'https://github.com/agkozak/zsh-z'
    dst: "{{ omz_custom_dir + '/zsh-z' }}"
  - url: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dst: "{{ omz_custom_dir + '/zsh-autocomplete' }}"
