---
- name: Get the command path
  shell:
    cmd: 'command -v pwsh'
  register: where_is_pwsh
  changed_when: 'where_is_pwsh.rc != 0'

- name: Make sure we can install from PSGallery
  shell:
    cmd: |
      if ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted')
      {
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      }
    executable: "{{ where_is_pwsh.stdout }}"
  register: ps_allow_psgallery
  changed_when: "ps_allow_psgallery.rc != 0"

- name: Make sure ps modules are installed
  shell:
    cmd: |
      if ('{{ item.name }}' -notin (Get-Module -ListAvailable | Select-Object -ExpandProperty Name))
      {
          Install-Module '{{ item.name }}' -Scope CurrentUser -AcceptLicense
      }
    executable: "{{ where_is_pwsh.stdout }}"
  register: ps_module_installed
  changed_when: "ps_module_installed.rc != 0"
  loop: "{{ ps_modules }}"
