---
- name: Build llvm clang clangd for Ubuntu 18 and up
  when: not fast | default(true)
  include_tasks: other.yml

- name: Install fast llvm clang clangd for Ubuntu 18 and up
  when: fast | default(false)
  include_tasks: repo.yml

# vim:et ts=2 sts=2 sw=2
