---
- name: Install some kernel modules
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
    update_cache: true
  loop:
    - linux-tools-common
    - linux-tools-generic

- name: Install more some kernel modules
  become: true
  when: ansible_kernel is match('.*generic')
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - "linux-cloud-tools-{{ ansible_kernel }}"
    - "linux-tools-{{ ansible_kernel }}"
