---
- name: Install system dependencies
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - git
    - curl

- name: Temp Patch to get around the https://github.com/ansible/ansible/issues/67972
  shell:
    cmd: git fetch --tags -f
    chdir: "{{ asdf_repos }}"
  register: git_fetch_asdf
  changed_when: git_fetch_asdf.rc != 0

- name: Get asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf_repos }}"
    clone: true
    version: "{{ asdf_repo_version | default('HEAD') }}"
    update: true

