---
- name: Get latest source code for git
  git:
    repo: https://github.com/git/git.git
    dest: "{{ git_repos }}"
    depth: 1
    clone: true
    version: "{{ git_repo_version | default('HEAD') }}"
    update: true
  register: git_clone_git

- name: Make sure local bin exist
  file:
    path: "{{ local_bin }}"
    state: directory

- name: Copy to ~/.local/bin and Make git-p4 executable
  when: git_clone_git.changed
  copy:
    src: "{{ git_repos + '/git-p4.py' }}"
    dest: "{{ local_bin + '/git-p4.py' }}"
    mode: 0755

- name: Edit the shabang to look for python3
  when: git_clone_git.changed
  lineinfile:
    dest: "{{ local_bin + '/git-p4.py' }}"
    regexp: '#!/usr/bin/env python'
    line: '#!/usr/bin/env python3'

# vim:et ts=2 sts=2 sw=2
