---
- name: Make sure autoload folder for fonts
  file:
    path: "{{ font_dir }}"
    state: directory

- name: Download and place the font
  get_url:
    url: "{{ firacode_url }}"
    dest: "{{ firacode_font }}"

- name: Refresh fonts
  shell:
    cmd: |
        fc-cache -vf "{{ font_dir }}"
  register: font_refresh
  changed_when: "font_refresh.rc != 0"
  failed_when: "font_refresh.rc != 0"
