---
- name: Make sure some system dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
    update_cache: true
  with_items:
    - fontconfig

- name: Make sure autoload folder for fonts
  file:
    path: "{{ font_dir }}"
    state: directory

- name: Download the fonts
  unarchive:
    remote_src: yes
    src: "{{ item }}"
    keep_newer: yes
    dest: "{{ font_dir }}"
  with_items: "{{ nerd_font_srcs }}"

- name: Refresh fonts
  shell:
    cmd: |
        fc-cache -vf "{{ font_dir }}"
  register: font_refresh
  changed_when: "font_refresh.rc != 0"
  failed_when: "font_refresh.rc != 0"
