---
- name: Install some kernel modules
  become: true
  apt:
    state: 'present'
    update_cache: true
    name:
      - linux-tools-common
      - linux-tools-generic

- name: Install more some kernel modules
  become: true
  when: ansible_kernel is match('.*generic')
  apt:
    state: 'present'
    name:
      - "linux-cloud-tools-{{ ansible_kernel }}"
      - "linux-tools-{{ ansible_kernel }}"
  register: kernel_linux_tool
  failed_when: "( ( 'No package matching' not in kernel_linux_tool.msg ) if ( 'msg' in kernel_linux_tool ) else false )"
