---
- name: Build cmake for Ubuntu 18 and up
  when: "(not fast | default(false)) and ansible_lsb.release != '24.04'"
  include_tasks: other.yml

- name: Install cmake for Ubuntu 18 and up
  when: fast | default(true)
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    state: present
    name:
      - cmake
      - cmake-docs

# vim:et ts=2 sts=2 sw=2
