---
- hosts: "{{ playbook_target }}"
  gather_facts: true
  roles:
    - common_settings
    - docker_install
    - dotfiles
    - scratch
    - some_git_clones

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - extra
  roles:
    - conda_install

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - rare
  roles:
    - brew_install
    - llvm_from_source
    - lttng_install
    - matlab_schemer
    - networking_tools

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - never
  roles:
    - kernel_tools
    - podman_install
    - qt_install
    - powershell_install
    - zsh_setup

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - broken
  roles:
    - fpga_dev
    - insync_install
    - netmakers_netclient
    - zerotier_install
    - home-manager

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - gui
  roles:
    - desktop
    - qtile
    - xmonad_wm

