---
- hosts: "{{ playbook_target }}"
  gather_facts: true
  roles:
    - common_settings
    - docker_install
    - dotfiles
    - scratch
    - some_git_clones

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - extra
  roles:
    - conda_install

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - rare
  roles:
    - brew_install
    - matlab_schemer
    - networking_tools

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - never
  roles:
    - podman_install
    - home-manager

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - broken
  roles:
    - lttng_install
    - insync_install

- hosts: "{{ playbook_target }}"
  gather_facts: true
  tags:
    - gui
  roles:
    - desktop
    - qtile
    - xmonad_wm

