---
- hosts: "{{ playbook_target }}"
  gather_facts: true
  roles:
    - common_settings
    - home-manager
    - scratch
    - docker_install
    - brew_install
    - dotfiles
    - llvm_from_source
    - lttng_install
    - matlab_schemer
    - networking_tools
    - nix_install
    - powershell_install
    - some_git_clones
    - zsh_setup

    # - conda_install
    # # - fpga_dev
    # # - insync_install
    # - kernel_tools
    # # - netmakers_netclient
    # - podman_install
    # - qt_install
    # # - zerotier_install

# - hosts: "{{ playbook_target }}"
#   gather_facts: true
#   tags:
#     - gui
#   roles:
#     - desktop
#     - qtile
#     - xmonad_wm
