---
- name: Make sure kitty repo exist
  file:
    path: "{{ kitty_repos }}"
    state: directory

- name: Make sure local bin exist
  file:
    path: "{{ local_bin }}"
    state: directory

- name: Make sure local bin exist
  file:
    path: "{{ kitty_desk_linked | dirname }}"
    state: directory

- name: Download the kitty
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    force: true
    dest: "{{ kitty_installer }}"
    mode: 0755

- name: Make sure some system dependencies are installed
  become: true
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    - python3
    - python3-dev
    - tar
    - xz-utils

- name: Install kitty
  shell:
    creates: "{{ kitty_bin }}"
    cmd: |
      {{ kitty_installer }} \
        dest={{ kitty_repos }} \
        launch=n

- name: Symlink the kitty bin
  file:
    path: "{{ kitty_bin_linked }}"
    src: "{{ kitty_bin }}"
    state: link

- name: Edit the desktop file icon
  lineinfile:
    path: "{{ kitty_desk }}"
    state: present
    regexp: 'Icon=.*'
    line: "Icon={{ kitty_icon }}"

- name: Edit the desktop file bin
  lineinfile:
    path: "{{ kitty_desk }}"
    state: present
    regexp: '^(Exec=).*'
    line: \g<1>{{ kitty_bin_linked }}
    backrefs: yes
    mode: '0755'

- name: Edit the desktop file bin 2
  lineinfile:
    path: "{{ kitty_desk }}"
    state: present
    regexp: '^(TryExec=).*'
    line: \g<1>{{ kitty_bin_linked }}
    backrefs: yes

- name: Symlink the kitty desktop
  file:
    path: "{{ kitty_desk_linked }}"
    src: "{{ kitty_desk }}"
    state: link
