---
- name: Install p4 from apt when available
  when: "(not fast | default(false)) and ansible_lsb.release != '24.04'"
  include_tasks: other.yml

- name: Install p4 p4v
  shell:
    cmd: |
      {{ nix_env_bin }} -iA nixpkgs.p4 nixpkgs.p4v nixpkgs.p4d
    executable: /bin/bash
  register: nix_install
  changed_when: 'nix_install.rc != 0'
  failed_when: 'nix_install.rc != 0'
