name: CI
on:
  push:
  schedule:
    - cron: '0 10 * * *'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['16', '18', '20']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run command
        run: "./rr.sh run-test ${{ matrix.os }}"
