name: CI
on:
  schedule:
    - cron: '0 10 * * *'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Run command
        run: ./rr.sh test
