name: CI
on:
  push:
  # schedule:
  #   - cron: '0 10 * * *'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  roles:
    strategy:
      matrix:
        role: [
          'home-manager',
          'scratch',
          'podman_install',
          'nix_install',
          'brew_install',
          'netmakers_netclient',
          'zeotier_install',
          'qt_install',
          'common_settings',
          'conda_install',
          'desktop',
          'doas_install',
          'dotfiles',
          'fpga_dev',
          'general_cargo_install',
          'kernel_tools',
          'llvm_from_source',
          'lttng_install',
          'matlab_schemer',
          'networking_tools',
          'p4',
          'powershell_install',
          'qtile',
          'some_git_clones',
          'xmonad_wm',
          'zsh_setup'
          ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Make it writable
        run: "chmod -R a+w ."
      - name: Run command
        run: "./rr.sh run-role 20 ${{ matrix.role }}"

  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['20', '18', '22']
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Run command
        run: "./rr.sh run-test ${{ matrix.os }}"
